"""
LangGraph State Model for Multi-Agent Feedback Loop

This module defines the state object that flows through the agent graph.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, TypedDict


class GraphState(TypedDict):
    """
    State object for the LangGraph multi-agent flow.

    This state is passed between agents and updated throughout the feedback loop.

    Attributes:
        raw_code: Original source code
        filename: Name of the file being analyzed
        language: Programming language
        mid_level_abstraction: Compressed semantic representation (output of Compressor)
        questions: List of questions generated by First-Time Reader
        file_intent: WHY the file exists (output of Explainer)
        responsibilities: WHAT the file does (output of Explainer)
        skeptic_feedback: Challenges and objections from Skeptic
        iteration_count: Number of feedback loop iterations completed
        is_complete: Whether the analysis has converged
        error: Optional error message if something fails
    """

    # Input data
    raw_code: str
    filename: str
    language: str

    # Intermediate artifacts
    mid_level_abstraction: Optional[Dict[str, Any]]
    questions: List[str]

    # Output artifacts
    file_intent: Optional[str]
    responsibilities: List[Dict[str, Any]]

    # Feedback loop state
    skeptic_feedback: Optional[Dict[str, Any]]
    iteration_count: int
    is_complete: bool

    # Error handling
    error: Optional[str]


def create_initial_state(raw_code: str, filename: str, language: str) -> GraphState:
    """
    Create initial state for the graph.

    Args:
        raw_code: Source code to analyze
        filename: Name of the file
        language: Programming language

    Returns:
        Initial GraphState with defaults
    """
    return GraphState(
        raw_code=raw_code,
        filename=filename,
        language=language,
        mid_level_abstraction=None,
        questions=[],
        file_intent=None,
        responsibilities=[],
        skeptic_feedback=None,
        iteration_count=0,
        is_complete=False,
        error=None,
    )
